In [1]:
%matplotlib notebook
import requests
import json
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
client_id = r'fd388b96c2804acc849e66d03c898c07'
client_secret = r'6971e5936216cae8695169ea88f866b0e6e277069f58419bff49d9c131ca8510'

auth_data = {
    'grant_type'    : 'client_credentials',
    'client_id'     : client_id,
    'client_secret' : client_secret,
    'scope'         : 'read_content read_financial_data read_product_data read_user_profile'
}

# create session instance
session = requests.Session()

# update session headers
session.headers.update({'Authorization':'Bearer '+ '56xlmtJK8dcsTty7ejMKkpRwFI8y'})
asset_id = 'MA4B66MW5E27U8P32SB'

request_url = "https://api.marquee.gs.com/v1/data/TREOD/query"

request_query = {
                    "where": {
                        "assetId": ["MA4B66MW5E27UANEQ6Q"]
                    },
                    "startDate": "2016-01-15",
                    "endDate":"2019-01-15"
               }

request = session.post(url=request_url, json=request_query)
results = json.loads(request.text)
table = pd.DataFrame(results['data'])

In [3]:
table

,adjustedAskPrice,adjustedBidPrice,adjustedHighPrice,adjustedLowPrice,adjustedOpenPrice,adjustedTradePrice,adjustedVolume,askPrice,assetId,bidPrice,date,highPrice,lowPrice,openPrice,tradePrice,updateTime,volume
0,204.99,204.83,205.0700,NaN,198.9700,204.990,5578640.0,204.99,MA4B66MW5E27UANEQ6Q,204.83,2016-01-15,205.0700,NaN,198.9700,204.990,2017-12-20T00:00:01Z,5578640.0
1,204.72,204.71,210.4700,NaN,208.7100,204.720,4038676.0,204.72,MA4B66MW5E27UANEQ6Q,204.71,2016-01-19,210.4700,NaN,208.7100,204.720,2017-12-20T00:00:01Z,4038676.0
2,198.70,198.43,201.2800,NaN,199.4000,198.700,5838608.0,198.70,MA4B66MW5E27UANEQ6Q,198.43,2016-01-20,201.2800,NaN,199.4000,198.700,2017-12-20T00:00:01Z,5838608.0
3,199.97,199.80,203.2300,NaN,201.5500,199.970,3166159.0,199.97,MA4B66MW5E27UANEQ6Q,199.80,2016-01-21,203.2300,NaN,201.5500,199.970,2017-12-20T00:00:01Z,3166159.0
4,202.55,202.54,205.5000,NaN,204.8005,202.550,3124055.0,202.55,MA4B66MW5E27UANEQ6Q,202.54,2016-01-22,205.5000,NaN,204.8005,202.550,2017-12-20T00:00:01Z,3124055.0
5,196.38,196.23,203.5700,NaN,200.0600,196.380,2698739.0,196.38,MA4B66MW5E27UANEQ6Q,196.23,2016-01-25,203.5700,NaN,200.0600,196.380,2017-12-20T00:00:01Z,2698739.0
6,193.56,193.51,197.8200,NaN,196.7000,193.560,4964180.0,193.56,MA4B66MW5E27UANEQ6Q,193.51,2016-01-26,197.8200,NaN,196.7000,193.560,2017-12-20T00:00:01Z,4964180.0
7,188.10,188.07,193.2600,NaN,192.3800,188.070,3617221.0,188.10,MA4B66MW5E27UANEQ6Q,188.07,2016-01-27,193.2600,NaN,192.3800,188.070,2017-12-20T00:00:01Z,3617221.0
8,189.71,189.63,191.2800,NaN,190.7900,189.700,4592754.0,189.71,MA4B66MW5E27UANEQ6Q,189.63,2016-01-28,191.2800,NaN,190.7900,189.700,2017-12-20T00:00:01Z,4592754.0
9,191.11,191.10,193.7400,NaN,189.9500,191.200,2852289.0,191.11,MA4B66MW5E27UANEQ6Q,191.10,2016-01-29,193.7400,NaN,189.9500,191.200,2017-12-20T00:00:01Z,2852289.0
10,197.09,196.94,199.5200,NaN,188.7600,196.940,5297639.0,197.09,MA4B66MW5E27UANEQ6Q,196.94,2016-02-01,199.5200,NaN,188.7600,196.940,2017-12-20T00:00:01Z,5297639.0
11,182.71,182.65,193.1200,NaN,192.4200,182.780,5773637.0,182.71,MA4B66MW5E27UANEQ6Q,182.65,2016-02-02,193.1200,NaN,192.4200,182.780,2017-12-20T00:00:01Z,5773637.0
12,173.48,173.41,183.9400,NaN,183.5900,173.480,7931362.0,173.48,MA4B66MW5E27UANEQ6Q,173.41,2016-02-03,183.9400,NaN,183.5900,173.480,2017-12-20T00:00:01Z,7931362.0
13,175.33,175.24,175.9800,NaN,170.7000,175.330,4385366.0,175.33,MA4B66MW5E27UANEQ6Q,175.24,2016-02-04,175.9800,NaN,170.7000,175.330,2017-12-20T00:00:01Z,4385366.0
14,162.60,162.59,173.0000,NaN,171.3000,162.600,9437591.0,162.60,MA4B66MW5E27UANEQ6Q,162.59,2016-02-05,173.0000,NaN,171.3000,162.600,2017-12-20T00:00:01Z,9437591.0
15,148.05,148.00,157.1500,NaN,157.1050,147.990,9312988.0,148.05,MA4B66MW5E27UANEQ6Q,148.00,2016-02-08,157.1500,NaN,157.1050,147.990,2017-12-20T00:00:01Z,9312988.0
16,148.13,148.11,159.7900,NaN,142.3200,148.250,8651648.0,148.13,MA4B66MW5E27UANEQ6Q,148.11,2016-02-09,159.7900,NaN,142.3200,148.250,2017-12-20T00:00:01Z,8651648.0
17,143.67,143.59,154.9700,NaN,150.5000,143.670,10406513.0,143.67,MA4B66MW5E27UANEQ6Q,143.59,2016-02-10,154.9700,NaN,150.5000,143.670,2017-12-20T00:00:01Z,10406513.0
18,150.70,150.42,163.2600,NaN,152.0000,150.470,14252364.0,150.70,MA4B66MW5E27UANEQ6Q,150.42,2016-02-11,163.2600,NaN,152.0000,150.470,2017-12-20T00:00:01Z,14252364.0
19,151.04,150.99,157.0100,NaN,155.0000,151.040,7235783.0,151.04,MA4B66MW5E27UANEQ6Q,150.99,2016-02-12,157.0100,NaN,155.0000,151.040,2017-12-20T00:00:01Z,7235783.0
20,155.15,154.98,162.9500,NaN,158.7000,155.170,5593794.0,155.15,MA4B66MW5E27UANEQ6Q,154.98,2016-02-16,162.9500,NaN,158.7000,155.170,2017-12-20T00:00:01Z,5593794.0
21,168.85,168.75,169.3400,NaN,159.0000,168.680,5825159.0,168.85,MA4B66MW5E27UANEQ6Q,168.75,2016-02-17,169.3400,NaN,159.0000,168.680,2017-12-20T00:00:01Z,5825159.0
22,166.75,166.61,172.9500,NaN,172.4200,166.770,3887574.0,166.75,MA4B66MW5E27UANEQ6Q,166.61,2016-02-18,172.9500,NaN,172.4200,166.770,2017-12-20T00:00:01Z,3887574.0
23,166.51,166.41,167.4900,NaN,163.6600,166.580,2959390.0,166.51,MA4B66MW5E27UANEQ6Q,166.41,2016-02-19,167.4900,NaN,163.6600,166.580,2017-12-20T00:00:01Z,2959390.0
24,177.74,177.72,178.9100,NaN,170.1200,177.740,5060051.0,177.74,MA4B66MW5E27UANEQ6Q,177.72,2016-02-22,178.9100,NaN,170.1200,177.740,2017-12-20T00:00:01Z,5060051.0
25,177.47,177.21,181.7300,NaN,176.1600,177.210,5984374.0,177.47,MA4B66MW5E27UANEQ6Q,177.21,2016-02-23,181.7300,NaN,176.1600,177.210,2017-12-20T00:00:01Z,5984374.0
26,178.98,178.78,179.5000,NaN,172.7500,179.000,5395609.0,178.98,MA4B66MW5E27UANEQ6Q,178.78,2016-02-24,179.5000,NaN,172.7500,179.000,2017-12-20T00:00:01Z,5395609.0
27,187.68,187.65,188.5192,NaN,178.6500,187.430,5750741.0,187.68,MA4B66MW5E27UANEQ6Q,187.65,2016-02-25,188.5192,NaN,178.6500,187.430,2017-12-20T00:00:01Z,5750741.0
28,190.46,190.34,192.0000,NaN,188.7000,190.340,6065117.0,190.46,MA4B66MW5E27UANEQ6Q,190.34,2016-02-26,192.0000,NaN,188.7000,190.340,2017-12-20T00:00:01Z,6065117.0
29,191.92,191.67,196.3500,NaN,192.4000,191.930,4498997.0,191.92,MA4B66MW5E27UANEQ6Q,191.67,2016-02-29,196.3500,NaN,192.4000,191.930,2017-12-20T00:00:01Z,4498997.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,350.40,350.33,351.6000,338.2648,341.8300,350.480,5628895.0,350.40,MA4B66MW5E27UANEQ6Q,350.33,2018-11-30,351.6000,338.2648,341.8300,350.480,2018-12-01T03:23:00Z,5628895.0
726,358.63,358.49,366.0000,352.0000,360.0000,358.490,8306511.0,358.63,MA4B66MW5E27UANEQ6Q,358.49,2018-12-03,366.0000,352.0000,360.0000,358.490,2018-12-04T03:05:00Z,8306511.0
727,359.70,359.50,368.6800,352.0000,356.0500,359.700,8461945.0,359.70,MA4B66MW5E27UANEQ6Q,359.50,2018-12-04,368.6800,352.0000,356.0500,359.700,2018-12-05T02:29:00Z,8461945.0
728,363.06,363.05,367.3800,350.7600,356.0100,363.060,7842508.0,363.06,MA4B66MW5E27UANEQ6Q,363.05,2018-12-06,367.3800,350.7600,356.0100,363.060,2018-12-07T02:42:00Z,7842508.0
729,357.97,357.96,379.4900,357.6500,369.0000,357.965,11511177.0,357.97,MA4B66MW5E27UANEQ6Q,357.96,2018-12-07,379.4900,357.6500,369.0000,357.965,2018-12-08T03:39:00Z,11511177.0
730,365.15,365.14,365.9800,353.1200,360.0000,365.150,6613455.0,365.15,MA4B66MW5E27UANEQ6Q,365.14,2018-12-10,365.9800,353.1200,360.0000,365.150,2018-12-11T02:27:00Z,6613455.0
731,366.69,366.56,372.1689,360.2300,369.9100,366.760,6308769.0,366.69,MA4B66MW5E27UANEQ6Q,366.56,2018-12-11,372.1689,360.2300,369.9100,366.760,2018-12-12T02:32:00Z,6308769.0
732,366.58,366.36,371.9100,365.1600,369.4200,366.600,5027048.0,366.58,MA4B66MW5E27UANEQ6Q,366.36,2018-12-12,371.9100,365.1600,369.4200,366.600,2018-12-13T02:25:00Z,5027048.0
733,376.96,376.79,377.4400,366.7500,370.1500,376.790,7365854.0,376.96,MA4B66MW5E27UANEQ6Q,376.79,2018-12-13,377.4400,366.7500,370.1500,376.790,2018-12-14T02:19:00Z,7365854.0
734,365.71,365.61,377.8700,364.3300,375.0000,365.710,6337555.0,365.71,MA4B66MW5E27UANEQ6Q,365.61,2018-12-14,377.8700,364.3300,375.0000,365.710,2018-12-15T03:25:00Z,6337555.0
735,348.42,348.36,365.7000,343.8800,362.0000,348.420,7674008.0,348.42,MA4B66MW5E27UANEQ6Q,348.36,2018-12-17,365.7000,343.8800,362.0000,348.420,2018-12-18T02:28:00Z,7674008.0
736,337.02,336.83,351.5500,333.6900,350.5400,337.030,7099999.0,337.02,MA4B66MW5E27UANEQ6Q,336.83,2018-12-18,351.5500,333.6900,350.5400,337.030,2018-12-19T02:22:00Z,7099999.0
737,332.97,332.70,347.0100,329.7400,337.6000,332.970,8274181.0,332.97,MA4B66MW5E27UANEQ6Q,332.70,2018-12-19,347.0100,329.7400,337.6000,332.970,2018-12-20T02:42:00Z,8274181.0
738,315.38,315.09,330.2900,311.8690,327.0535,315.380,9071858.0,315.38,MA4B66MW5E27UANEQ6Q,315.09,2018-12-20,330.2900,311.8690,327.0535,315.380,2018-12-21T02:07:00Z,9071858.0
739,319.99,319.82,323.4700,312.4400,317.4000,319.770,8016801.0,319.99,MA4B66MW5E27UANEQ6Q,319.82,2018-12-21,323.4700,312.4400,317.4000,319.770,2018-12-22T02:44:00Z,8016801.0
740,295.67,295.46,314.5000,295.1950,313.5000,295.390,5559913.0,295.67,MA4B66MW5E27UANEQ6Q,295.46,2018-12-24,314.5000,295.1950,313.5000,295.390,2018-12-25T02:25:00Z,5559913.0
741,326.08,325.90,326.9700,294.0900,300.0000,326.090,8163138.0,326.08,MA4B66MW5E27UANEQ6Q,325.90,2018-12-26,326.9700,294.0900,300.0000,326.090,2018-12-27T02:29:00Z,8163138.0
742,316.13,315.92,322.1717,301.5000,319.8400,316.130,8575133.0,316.13,MA4B66MW5E27UANEQ6Q,315.92,2018-12-27,322.1717,301.5000,319.8400,316.130,2018-12-28T02:20:00Z,8575133.0
743,334.00,333.87,336.2400,318.4100,323.1000,333.870,9938992.0,334.00,MA4B66MW5E27UANEQ6Q,333.87,2018-12-28,336.2400,318.4100,323.1000,333.870,2018-12-29T03:08:00Z,9938992.0
744,332.89,332.88,339.2100,325.2600,337.7900,332.800,6302338.0,332.89,MA4B66MW5E27UANEQ6Q,332.88,2018-12-31,339.2100,325.2600,337.7900,332.800,2019-01-01T02:40:00Z,6302338.0
745,310.09,310.08,315.1300,298.8000,306.1000,310.120,11658648.0,310.09,MA4B66MW5E27UANEQ6Q,310.08,2019-01-02,315.1300,298.8000,306.1000,310.120,2019-01-03T02:11:00Z,11658648.0
746,300.36,300.35,309.4000,297.3800,307.0000,300.360,6965184.0,300.36,MA4B66MW5E27UANEQ6Q,300.35,2019-01-03,309.4000,297.3800,307.0000,300.360,2019-01-04T02:26:00Z,6965184.0
747,317.69,317.56,318.0000,302.7300,306.0000,317.690,7394116.0,317.69,MA4B66MW5E27UANEQ6Q,317.56,2019-01-04,318.0000,302.7300,306.0000,317.690,2019-01-05T03:35:00Z,7394116.0
748,334.97,334.81,336.7400,317.7508,321.7200,334.960,7551225.0,334.97,MA4B66MW5E27UANEQ6Q,334.81,2019-01-07,336.7400,317.7508,321.7200,334.960,2019-01-08T02:26:00Z,7551225.0
749,335.32,335.29,344.0100,327.0200,341.9600,335.350,7008516.0,335.32,MA4B66MW5E27UANEQ6Q,335.29,2019-01-08,344.0100,327.0200,341.9600,335.350,2019-01-09T02:38:00Z,7008516.0
750,338.49,338.42,343.5025,331.4700,335.5000,338.530,5432945.0,338.49,MA4B66MW5E27UANEQ6Q,338.42,2019-01-09,343.5025,331.4700,335.5000,338.530,2019-01-10T02:45:00Z,5432945.0
751,344.98,344.90,345.3900,331.7900,334.4000,344.970,6056354.0,344.98,MA4B66MW5E27UANEQ6Q,344.90,2019-01-10,345.3900,331.7900,334.4000,344.970,2019-01-11T02:09:00Z,6056354.0
752,347.23,347.22,348.4100,338.7700,342.0900,347.260,5039052.0,347.23,MA4B66MW5E27UANEQ6Q,347.22,2019-01-11,348.4100,338.7700,342.0900,347.260,2019-01-12T03:21:00Z,5039052.0
753,334.49,334.40,342.5000,334.0000,342.3800,334.400,5247284.0,334.49,MA4B66MW5E27UANEQ6Q,334.40,2019-01-14,342.5000,334.0000,342.3800,334.400,2019-01-15T02:15:00Z,5247284.0
754,344.36,344.21,348.8000,334.5000,335.0000,344.430,6056590.0,344.36,MA4B66MW5E27UANEQ6Q,344.21,2019-01-15,348.8000,334.5000,335.0000,344.430,2019-01-16T02:23:00Z,6056590.0

In [4]:
tesla = table[['date', 'adjustedHighPrice', 'adjustedLowPrice', 'adjustedOpenPrice', 'tradePrice', 'volume', 'adjustedTradePrice']]

In [5]:
tesla.columns = ['Date', 'High','Low', 'Open', 'Close', 'Volume', 'Adj Close']
tesla.set_index('Date', inplace=True)
tesla.index = pd.to_datetime(tesla.index)

In [6]:
#### Trading Strategy ####
def trading_strategy():
    # Initialize the short and long windows
    short_window = 40
    long_window = 100
    # Initialize the `signals` DataFrame with the `signal` column
    signals = pd.DataFrame(index=tesla.index)
    signals['signal'] = 0.0
    # Create short simple moving average over the short window
    signals['short_mavg'] = tesla['Close'].rolling(window=short_window, min_periods=1, center=False).mean()
    # Create long simple moving average over the long window
    signals['long_mavg'] = tesla['Close'].rolling(window=long_window, min_periods=1, center=False).mean()
    # Create signals
    signals['signal'][short_window:] = np.where(signals['short_mavg'][short_window:] 
                                                > signals['long_mavg'][short_window:], 1.0, 0.0)   
    # Generate trading orders
    signals['positions'] = signals['signal'].diff()
    
    return signals


#### Backtesting ####
def backtesting(signals):
    # Set the initial capital
    initial_capital= float(100000.0)
    # Create a DataFrame `positions`
    positions = pd.DataFrame(index=signals.index).fillna(0.0)
    # Buy a 100 shares
    positions['TSLA'] = 100*signals['signal']   
    # Initialize the portfolio with value owned   
    portfolio = positions.multiply(tesla['Adj Close'], axis=0)
    # Store the difference in shares owned 
    pos_diff = positions.diff()
    # Add `holdings` to portfolio
    portfolio['holdings'] = (positions.multiply(tesla['Adj Close'], axis=0)).sum(axis=1)
    # Add `cash` to portfolio
    portfolio['cash'] = initial_capital - (pos_diff.multiply(tesla['Adj Close'], axis=0)).sum(axis=1).cumsum()   
    # Add `total` to portfolio
    portfolio['total'] = portfolio['cash'] + portfolio['holdings']
    # Add `returns` to portfolio
    portfolio['returns'] = portfolio['total'].pct_change()
    
    return portfolio


#### Sharpe Ratio ####
def sharpe_ratio(portfolio):
    # Isolate the returns of your strategy
    returns = portfolio['returns']
    # annualized Sharpe ratio
    sharpe_ratio = np.sqrt(252) * (returns.mean() / returns.std())
    
    return sharpe_ratio

#### Compound Annual Growth Rate ####
def cagr():
    # Get the number of days in `tesla`
    days = (tesla.index[-1] - tesla.index[0]).days
    # Calculate the CAGR 
    cagr = ((((tesla['Adj Close'][-1]) / tesla['Adj Close'][1])) ** (365.0/days)) - 1
    
    return cagr

#### Extract Buy/Sell signals ####
def extract_signals(signals, indicator):
    locs = signals.loc[signals.positions == indicator].index
    prices = signals.short_mavg[signals.positions == indicator]
    
    return locs, signals

#### Sentiment Score ####
def sentiment_score(positives, negatives):
    total = postives + negatives
    cumulative = postives - negatives
    return cumulative / total
    
    
signals = trading_strategy()
portfolio = backtesting(signals)
sharpe_ratio = sharpe_ratio(portfolio)
cagr = cagr()

sns.set()

# Initialize the plot figure
fig = plt.figure(1)
# Add a subplot and label for y-axis
ax1 = fig.add_subplot(111,  ylabel='Price in $')
# Plot the closing price
tesla['Close'].plot(ax=ax1, color='r', lw=2.)
# Plot the short and long moving averages
signals[['short_mavg', 'long_mavg']].plot(ax=ax1, lw=2.)
# Plot the buy signals
ax1.plot(signals.loc[signals.positions == 1.0].index, 
         signals.short_mavg[signals.positions == 1.0],
         '^', markersize=10, color='m')         
# Plot the sell signals
ax1.plot(signals.loc[signals.positions == -1.0].index, 
         signals.short_mavg[signals.positions == -1.0],
         'v', markersize=10, color='k') 
plt.title("Algorithmic Trading Strategy")
# Show the plot
plt.show()

print("Sharpe Ratio: ", round(sharpe_ratio, 3))
print("Compound Annual Growth Rate: ", round(cagr, 3))

NameError: name 'maximum_drawdown' is not defined